### ISSUE TITLE
Missing Book XIII in the "Pan Tadeusz" Repository

### ISSUE THREAD

**Issue by MaciejWiatr** [Jakub-Wilk/PanTadeusz#1]
Dear maintainers of the "Pan Tadeusz" repository,

I would like to bring to your attention that there seems to be a crucial issue with the current version of the repository. Upon inspection, I have noticed that the repository is missing Book XIII of the famous Polish epic poem "Pan Tadeusz" by Adam Mickiewicz.

As Book XIII is an integral part of the poem, its absence greatly impacts the completeness and accuracy of the repository. I believe it is important to address this issue and add Book XIII to the repository as soon as possible.

I kindly request that the maintainers of the repository take the necessary steps to resolve this issue and ensure that the repository contains the complete text of "Pan Tadeusz" including all its books.

Thank you for your attention to this matter.

Best regards,
Maciej Wiatr

**Comment by Jakub-Wilk** [comment]
Dear @MaciejWiatr,

As maintainers of a repository containing and preserving such a culturally significant artifact of Polish literature, we find it extraordinarily important to cultivate a historically accurate approach to our preservation efforts.

As such, we cannot in good heart consider adding Book XIII to our collection, as it is not part of the original work, rather being added later by a separate author.

Nevertheless, thank you for your concern and keep being curious!
